// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoGP.API.DBContext;

#nullable disable

namespace MotoGP.API.Migrations
{
    [DbContext(typeof(MotoGPContext))]
    [Migration("20250318122745_AddTicketEntity")]
    partial class AddTicketEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotoGP.API.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Antigua"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Burkina"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Burma"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 35,
                            Name = "China"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Cote d'Ivoire"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 51,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 58,
                            Name = "France"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 77,
                            Name = "India"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Irish Republic"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Kirgizstan"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Korea (North)"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Korea (South)"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 124,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Saint Kitts"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Saint Vincent"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 147,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 158,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Tahiti"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 182,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 183,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 189,
                            Name = "White Russia"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Zaire"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("MotoGP.API.Entities.Rider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("TeamId");

                    b.ToTable("Riders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 159,
                            FirstName = "Hector",
                            LastName = "Barbera",
                            Number = 8,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 58,
                            FirstName = "Mike",
                            LastName = "Di Meglio",
                            Number = 63,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 44,
                            FirstName = "Karel",
                            LastName = "Abraham",
                            Number = 17,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 85,
                            FirstName = "Hiroshi",
                            LastName = "Aoyama",
                            Number = 7,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 183,
                            FirstName = "Niki",
                            LastName = "Hayden",
                            Number = 69,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 83,
                            FirstName = "Andrea",
                            LastName = "Dovizioso",
                            Number = 4,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 182,
                            FirstName = "Cal",
                            LastName = "Crutchlow",
                            Number = 35,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 182,
                            FirstName = "Leon",
                            LastName = "Camier",
                            Number = 2,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 83,
                            FirstName = "Danilo",
                            LastName = "Petrucci",
                            Number = 9,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 62,
                            FirstName = "Stefan",
                            LastName = "Bradl",
                            Number = 6,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 159,
                            FirstName = "Dani",
                            LastName = "Pedrosa",
                            Number = 26,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 159,
                            FirstName = "Marc",
                            LastName = "Marquez",
                            Number = 93,
                            TeamId = 5
                        });
                });

            modelBuilder.Entity("MotoGP.API.Entities.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OfficialWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Logo = "qatar.png",
                            Name = "Qatar Airways",
                            OfficialWebsite = "https://www.qatarairways.com/es-es/homepage.html"
                        },
                        new
                        {
                            Id = 2,
                            Logo = "bmw.png",
                            Name = "BMW",
                            OfficialWebsite = "https://www.bmw-m.com/en/fastlane/motogp.html"
                        },
                        new
                        {
                            Id = 3,
                            Logo = "tissot.png",
                            Name = "Tissot",
                            OfficialWebsite = "https://www.tissotwatches.com/"
                        },
                        new
                        {
                            Id = 4,
                            Logo = "estrella.png",
                            Name = "Estrella Galicia",
                            OfficialWebsite = "https://estrellagalicia00.es/"
                        },
                        new
                        {
                            Id = 5,
                            Logo = "michelin.png",
                            Name = "Michelin",
                            OfficialWebsite = "https://www.michelinmotorsport.com/en/motorsport/"
                        },
                        new
                        {
                            Id = 6,
                            Logo = "dhl.png",
                            Name = "DHL",
                            OfficialWebsite = "https://www.dhl.com/global-en/home/about-us/partnerships.html"
                        });
                });

            modelBuilder.Entity("MotoGP.API.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Logo = "Avintia.png",
                            Name = "Avintia Racing"
                        },
                        new
                        {
                            Id = 2,
                            Logo = "AB.png",
                            Name = "Cardion AB Motoracing"
                        },
                        new
                        {
                            Id = 3,
                            Logo = "Ducati.png",
                            Name = "Ducati Team"
                        },
                        new
                        {
                            Id = 4,
                            Logo = "LCR.png",
                            Name = "LCR Honda MotoGP"
                        },
                        new
                        {
                            Id = 5,
                            Logo = "Repsol.png",
                            Name = "Repsol Honda Team"
                        },
                        new
                        {
                            Id = 6,
                            Logo = "M7.png",
                            Name = "Drive M7 Aspar"
                        },
                        new
                        {
                            Id = 7,
                            Logo = "ioda.png",
                            Name = "IodaRacing Project"
                        });
                });

            modelBuilder.Entity("Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Assen is the only venue to have held a round of the Motorcycle World Championship every year since its creation in 1949. The circuit was purpose built for the Dutch TT in 1954, with previous events having been held on public roads. The track is narrow, with rapid changes in direction, and is fully surrounded by grass banks and grandstands, providing excellent viewing for the hundreds of thousands of fanatical spectators who are drawn to the most prestigious event in Dutch motorsport every year. A huge favourite with riders, Assen is well known for its festive and extravagant atmosphere.",
                            Length = 4542,
                            Name = "TT Circuit Assen",
                            Place = "Assen (Netherlands)",
                            X = 517,
                            Y = 19
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The fabulous Losail International Circuit lies on the outskirts of Doha, the capital city of Qatar. Built in little over a year, the track cost $58 million USD and required round-the-clock dedication from almost 1,000 workers in order to get it ready for the inaugural event - the Marlboro Grand Prix of Qatar on the 2nd October 2004.",
                            Length = 5380,
                            Name = "Losail Circuit",
                            Place = "Doha (Qatar)",
                            X = 859,
                            Y = 249
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "One of its more distinctive features is near 41m-elevation change with an impressive incline at the end of the home-straight followed by a sharp left. The circuit is one of the most varied on the GP circuit, with a mix of fast straights and tight hairpins, with most sections mirroring at least some part of a famous track around the world.",
                            Length = 5201,
                            Name = "Autódromo Termas de Río Hondo",
                            Place = "Río Hondo (Argentina)",
                            X = 194,
                            Y = 428
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Built in 1986 and hosting its first Grand Prix one year later, the circuit of Jerez is now one of the most popular MotoGP venues and the focal point for a city fanatical about sport. Set in a slight valley in the south of Spain, Jerez is blessed with consistently good weather and beautiful scenery, its numerous grandstands providing the perfect viewing facilities for up to 250,000 spectators.",
                            Length = 4423,
                            Name = "Circuito Permanente de Jerez",
                            Place = "Jerez (Spain)",
                            X = 342,
                            Y = 169
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Le Mans is a tight track dominated by first gear corners that place the emphasis on late braking and hard acceleration, whilst rear end traction is also a key area. With the capacity to comfortably accommodate up to 100,000 spectators, the Bugatti circuit also plays host to the 24 hour truck race, the FIA GP2 Championship, French Touring Car and GT races.",
                            Length = 4185,
                            Name = "Circuit de la Sarthe",
                            Place = "Le Mans (France)",
                            X = 564,
                            Y = 161
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Car and bike races have been held on closed public roads in the area around the town of Chemnitz, Germany since the 1920s and were still taking place until as recently as 1990. It was decided, however, that the five mile course through such a densely populated area was no longer suitable and a new circuit was built five miles west of Chemnitz in 1996. Although mainly used as a driver training centre and road transport safety station, Sachsenring first hosted MotoGP in 1998 and many improvements have taken place since then, including a drastic layout enhancement in 2001. Numerous tight corners make it one of the slower tracks on the calendar but there is never any shortage of close racing action.",
                            Length = 3671,
                            Name = "Sachsenring",
                            Place = "Hohenstein-Ernstthal (Germany)",
                            X = 645,
                            Y = 53
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The first motorsport race which took place at Indy was a motorcycle one on August 14th 1909, on the 2.5 mile oval circuit, and despite its 100-year history it was not until 2008 that MotoGP arrived at the Indianapolis Motor Speedway.",
                            Length = 4216,
                            Name = "Indianapolis Motor Speedway",
                            Place = "Indianapolis (United States)",
                            X = 21,
                            Y = 114
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "With more than 60 years of history Silverstone has become one of the most prestigious venues dedicated to motorsport. Completely revamped in recent years, a multimillion pound investment saw the completion in 2010 of a first phase of works to greatly improve the venue, making it one of the fastest tracks on the MotoGP calendar and earning high praise from the World Championship riders who enjoyed the new layout. The ‘Silverstone Wing’, a state-of-the-art, multi-million pound complex, became a new landmark at the circuit from 2011, thus adding to already breathtaking facilities at Silverstone.",
                            Length = 5900,
                            Name = "Silverstone Circuit",
                            Place = "Silverstone (Great Britain)",
                            X = 354,
                            Y = 69
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2025, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Close to the city of Rimini, the Misano Adriático circuit was constructed in 1972 and has since undergone an array of modifications. A regular scene for Italian Grands Prix throughout the 80s and early 90s, Misano returned to the MotoGP calendar in 2007.With updated facilities, track and grandstands, the Misano Adriatico holds a maximum capacity of 60,000 spectators. In accordance with MotoGP safety regulations, the 4,200m track runs clockwise for the World Championship races.",
                            Length = 4226,
                            Name = "World Circuit Marco Simoncelli",
                            Place = "Misano (Italy)",
                            X = 502,
                            Y = 337
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Located amongst the vast natural beauty of the northern Kanto district, the twin ring circuit at Motegi in Japan consists of a 1.5 mile oval and a 2.9 mile road course constructed to international standards. Built by Honda as the ultimate test facility in August 1997, the road circuit became home to MotoGP in 2000 whilst the oval is designed to introduce American motorsports culture to the country.",
                            Length = 4801,
                            Name = "Twin Ring",
                            Place = "Motegi (Japan)",
                            X = 921,
                            Y = 132
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Specifically built for speed and exciting racing, the Sepang International Circuit in Malaysia is one of the world’s best. The 2,300 acre complex which also houses a hotel, shopping centre, golf course and other sports facilities cost around £50m to construct and was built in just 14 months, holding its first Grand Prix in April 1999 and setting the standard for race circuits worldwide.",
                            Length = 5548,
                            Name = "Sepang Circuit",
                            Place = "Sepang (Malaysia)",
                            X = 700,
                            Y = 275
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Circuito de la Comunitat Valenciana was completed in 1999 and held rounds of the MotoGP and Spanish Motorcycle Championships in the same year. The Cheste track has several layouts, running anti-clockwise with varying lengths. MotoGP events are held on a 4km track comprising of five right handed corners, eight left handers and a 650m straight. Although the track is regarded as quite small, the pit complex contains 48 garages whilst the stadium style grandstands can seat up to 150,000 spectators. The circuit layout which allows all parts of the circuit to be seen from any stand helps to create a unique atmosphere enjoyed by Spanish and international riders alike and as the last race of the season there is always a party feeling to the Grand Prix, which was voted best GP of 2005 by IRTA.",
                            Length = 4005,
                            Name = "Comunitat Valenciana",
                            Place = "Valencia (Spain)",
                            X = 649,
                            Y = 363
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Circuit of the Americas in Austin, Texas, is the first purpose-built Grand Prix facility in the USA, with a capacity for 120,000 fans. The track is 5.513 km long and includes 20 turns with an elevation change of 41 meters.",
                            Length = 5513,
                            Name = "Circuit of the Americas",
                            Place = "Austin (USA)",
                            X = 103,
                            Y = 253
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Autódromo Internacional Nelson Piquet, also known as Jacarepaguá, was a motorsport circuit in Rio de Janeiro, Brazil. It hosted the Brazilian Grand Prix and was known for its challenging layout and tropical weather conditions.",
                            Length = 5021,
                            Name = "Autódromo Internacional Nelson Piquet",
                            Place = "Rio de Janeiro (Brazil)",
                            X = 324,
                            Y = 429
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2025, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "MotorLand Aragón is a motorsport race track located near Alcañiz in Spain. It was designed by Hermann Tilke and the facility includes a technology park, a sports area, and a cultural and leisure area.",
                            Length = 5078,
                            Name = "MotorLand Aragón",
                            Place = "Aragon (Spain)",
                            X = 402,
                            Y = 134
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2025, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Circuit de Barcelona-Catalunya is located in Montmeló, Spain. It has hosted the Spanish Grand Prix since 1991 and is known for its combination of high and low-speed corners, making it a favorite among drivers and teams.",
                            Length = 4655,
                            Name = "Circuit de Barcelona-Catalunya",
                            Place = "Catalunya (Spain)",
                            X = 378,
                            Y = 239
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Misano World Circuit Marco Simoncelli is located next to the town of Misano Adriatico in the Province of Rimini. The circuit was renamed in honor of MotoGP rider Marco Simoncelli, who died in 2011.",
                            Length = 4226,
                            Name = "Misano World Circuit Marco Simoncelli",
                            Place = "San Marino (Italy)",
                            X = 426,
                            Y = 304
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Automotodrom Brno is a 5.403 km circuit located near Brno, Czech Republic. It has a rich history in motorsports and is known for its elevation changes and challenging layout.",
                            Length = 5403,
                            Name = "Automotodrom Brno",
                            Place = "Brno (Czech Republic)",
                            X = 685,
                            Y = 115
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Phillip Island Grand Prix Circuit is located on Phillip Island, Victoria. It is known for its stunning coastal views and high-speed corners, making it a favorite among riders and fans.",
                            Length = 4445,
                            Name = "Phillip Island Grand Prix Circuit",
                            Place = "Phillip Island (Australia)",
                            X = 736,
                            Y = 403
                        });
                });

            modelBuilder.Entity("TeamSponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamSponsors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SponsorId = 2,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            SponsorId = 3,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            SponsorId = 4,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            SponsorId = 5,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            SponsorId = 6,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 6,
                            SponsorId = 1,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            SponsorId = 3,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 8,
                            SponsorId = 4,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 9,
                            SponsorId = 5,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 10,
                            SponsorId = 6,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 11,
                            SponsorId = 1,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 12,
                            SponsorId = 2,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 13,
                            SponsorId = 4,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 14,
                            SponsorId = 5,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 15,
                            SponsorId = 6,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 16,
                            SponsorId = 1,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 17,
                            SponsorId = 2,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 18,
                            SponsorId = 3,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 19,
                            SponsorId = 5,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 20,
                            SponsorId = 6,
                            TeamId = 4
                        });
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("RaceId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "940 Edinburgh Street, Edinburgh",
                            CountryId = 182,
                            Email = "liam.thompson@example.com",
                            Name = "Liam Thompson",
                            Number = 1,
                            OrderDate = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = false,
                            RaceId = 3
                        },
                        new
                        {
                            Id = 2,
                            Address = "601 Bruges Street, Bruges",
                            CountryId = 15,
                            Email = "jasper.desmet@example.com",
                            Name = "Jasper De Smet",
                            Number = 2,
                            OrderDate = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = false,
                            RaceId = 12
                        },
                        new
                        {
                            Id = 3,
                            Address = "249 Birmingham Street, Birmingham",
                            CountryId = 182,
                            Email = "oliver.hughes@example.com",
                            Name = "Oliver Hughes",
                            Number = 1,
                            OrderDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = true,
                            RaceId = 10
                        },
                        new
                        {
                            Id = 4,
                            Address = "869 Johannesburg Street, Johannesburg",
                            CountryId = 158,
                            Email = "sipho.mokoena@example.com",
                            Name = "Sipho Mokoena",
                            Number = 2,
                            OrderDate = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = true,
                            RaceId = 9
                        },
                        new
                        {
                            Id = 5,
                            Address = "535 Houston Street, Houston",
                            CountryId = 183,
                            Email = "ethan.johnson@example.com",
                            Name = "Ethan Johnson",
                            Number = 2,
                            OrderDate = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = true,
                            RaceId = 6
                        },
                        new
                        {
                            Id = 6,
                            Address = "677 Stockholm Street, Stockholm",
                            CountryId = 164,
                            Email = "erik.larsson@example.com",
                            Name = "Erik Larsson",
                            Number = 1,
                            OrderDate = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = true,
                            RaceId = 15
                        },
                        new
                        {
                            Id = 7,
                            Address = "225 Birmingham Street, Birmingham",
                            CountryId = 182,
                            Email = "george.brown@example.com",
                            Name = "George Brown",
                            Number = 2,
                            OrderDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = false,
                            RaceId = 13
                        },
                        new
                        {
                            Id = 8,
                            Address = "769 Cape Town Street, Cape Town",
                            CountryId = 158,
                            Email = "thabo.dlamini@example.com",
                            Name = "Thabo Dlamini",
                            Number = 1,
                            OrderDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = true,
                            RaceId = 14
                        },
                        new
                        {
                            Id = 9,
                            Address = "898 Ghent Street, Ghent",
                            CountryId = 15,
                            Email = "lotte.vermeulen@example.com",
                            Name = "Lotte Vermeulen",
                            Number = 4,
                            OrderDate = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = true,
                            RaceId = 6
                        },
                        new
                        {
                            Id = 10,
                            Address = "901 Chicago Street, Chicago",
                            CountryId = 183,
                            Email = "emily.anderson@example.com",
                            Name = "Emily Anderson",
                            Number = 3,
                            OrderDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = true,
                            RaceId = 15
                        },
                        new
                        {
                            Id = 11,
                            Address = "770 Miami Street, Miami",
                            CountryId = 183,
                            Email = "mason.clark@example.com",
                            Name = "Mason Clark",
                            Number = 3,
                            OrderDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = false,
                            RaceId = 14
                        },
                        new
                        {
                            Id = 12,
                            Address = "199 Stockholm Street, Stockholm",
                            CountryId = 164,
                            Email = "anna.nilsson@example.com",
                            Name = "Anna Nilsson",
                            Number = 3,
                            OrderDate = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = true,
                            RaceId = 5
                        },
                        new
                        {
                            Id = 13,
                            Address = "241 Johannesburg Street, Johannesburg",
                            CountryId = 158,
                            Email = "nomsa.khumalo@example.com",
                            Name = "Nomsa Khumalo",
                            Number = 2,
                            OrderDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = true,
                            RaceId = 11
                        },
                        new
                        {
                            Id = 14,
                            Address = "712 Houston Street, Houston",
                            CountryId = 183,
                            Email = "lucas.martinez@example.com",
                            Name = "Lucas Martinez",
                            Number = 1,
                            OrderDate = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = false,
                            RaceId = 9
                        },
                        new
                        {
                            Id = 15,
                            Address = "228 Johannesburg Street, Johannesburg",
                            CountryId = 158,
                            Email = "bongani.nkosi@example.com",
                            Name = "Bongani Nkosi",
                            Number = 5,
                            OrderDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = true,
                            RaceId = 5
                        },
                        new
                        {
                            Id = 16,
                            Address = "320 Port Elizabeth Street, Port Elizabeth",
                            CountryId = 158,
                            Email = "annelies.peeters@example.com",
                            Name = "Annelies Peeters",
                            Number = 1,
                            OrderDate = new DateTime(2024, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = false,
                            RaceId = 11
                        },
                        new
                        {
                            Id = 17,
                            Address = "126 Malmö Street, Malmö",
                            CountryId = 164,
                            Email = "viktor.lindberg@example.com",
                            Name = "Viktor Lindberg",
                            Number = 3,
                            OrderDate = new DateTime(2024, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = true,
                            RaceId = 16
                        },
                        new
                        {
                            Id = 18,
                            Address = "212 Port Elizabeth Street, Port Elizabeth",
                            CountryId = 158,
                            Email = "pieter.janssens@example.com",
                            Name = "Pieter Janssens",
                            Number = 5,
                            OrderDate = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = false,
                            RaceId = 6
                        },
                        new
                        {
                            Id = 19,
                            Address = "57 Stockholm Street, Stockholm",
                            CountryId = 164,
                            Email = "fredrik.andersson@example.com",
                            Name = "Fredrik Andersson",
                            Number = 4,
                            OrderDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = false,
                            RaceId = 6
                        },
                        new
                        {
                            Id = 20,
                            Address = "569 Durban Street, Durban",
                            CountryId = 158,
                            Email = "jacob.smith@example.com",
                            Name = "Jacob Smith",
                            Number = 4,
                            OrderDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paid = true,
                            RaceId = 1
                        });
                });

            modelBuilder.Entity("MotoGP.API.Entities.Rider", b =>
                {
                    b.HasOne("MotoGP.API.Entities.Country", "Country")
                        .WithMany("Riders")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoGP.API.Entities.Team", "Team")
                        .WithMany("Riders")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamSponsor", b =>
                {
                    b.HasOne("MotoGP.API.Entities.Sponsor", "Sponsor")
                        .WithMany("TeamSponsors")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoGP.API.Entities.Team", "Team")
                        .WithMany("TeamSponsors")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sponsor");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.HasOne("MotoGP.API.Entities.Country", "Country")
                        .WithMany("Tickets")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Race", "Race")
                        .WithMany("Tickets")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("MotoGP.API.Entities.Country", b =>
                {
                    b.Navigation("Riders");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MotoGP.API.Entities.Sponsor", b =>
                {
                    b.Navigation("TeamSponsors");
                });

            modelBuilder.Entity("MotoGP.API.Entities.Team", b =>
                {
                    b.Navigation("Riders");

                    b.Navigation("TeamSponsors");
                });

            modelBuilder.Entity("Race", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
