// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoGP.API.DBContext;

#nullable disable

namespace MotoGP.API.Migrations
{
    [DbContext(typeof(MotoGPContext))]
    [Migration("20250312115945_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotoGP.API.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Antigua"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Burkina"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Burma"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 35,
                            Name = "China"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Cote d'Ivoire"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 51,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 58,
                            Name = "France"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 77,
                            Name = "India"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Irish Republic"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Kirgizstan"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Korea (North)"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Korea (South)"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 124,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Saint Kitts"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Saint Vincent"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 147,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 158,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Tahiti"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 182,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 183,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 189,
                            Name = "White Russia"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Zaire"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("MotoGP.API.Entities.Rider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("TeamId");

                    b.ToTable("Riders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 159,
                            FirstName = "Hector",
                            LastName = "Barbera",
                            Number = 8,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 58,
                            FirstName = "Mike",
                            LastName = "Di Meglio",
                            Number = 63,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 44,
                            FirstName = "Karel",
                            LastName = "Abraham",
                            Number = 17,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 85,
                            FirstName = "Hiroshi",
                            LastName = "Aoyama",
                            Number = 7,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 183,
                            FirstName = "Niki",
                            LastName = "Hayden",
                            Number = 69,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 83,
                            FirstName = "Andrea",
                            LastName = "Dovizioso",
                            Number = 4,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 182,
                            FirstName = "Cal",
                            LastName = "Crutchlow",
                            Number = 35,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 182,
                            FirstName = "Leon",
                            LastName = "Camier",
                            Number = 2,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 83,
                            FirstName = "Danilo",
                            LastName = "Petrucci",
                            Number = 9,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 62,
                            FirstName = "Stefan",
                            LastName = "Bradl",
                            Number = 6,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 159,
                            FirstName = "Dani",
                            LastName = "Pedrosa",
                            Number = 26,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 159,
                            FirstName = "Marc",
                            LastName = "Marquez",
                            Number = 93,
                            TeamId = 5
                        });
                });

            modelBuilder.Entity("MotoGP.API.Entities.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OfficialWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Logo = "qatar.png",
                            Name = "Qatar Airways",
                            OfficialWebsite = "https://www.qatarairways.com/es-es/homepage.html"
                        },
                        new
                        {
                            Id = 2,
                            Logo = "bmw.png",
                            Name = "BMW",
                            OfficialWebsite = "https://www.bmw-m.com/en/fastlane/motogp.html"
                        },
                        new
                        {
                            Id = 3,
                            Logo = "tissot.png",
                            Name = "Tissot",
                            OfficialWebsite = "https://www.tissotwatches.com/"
                        },
                        new
                        {
                            Id = 4,
                            Logo = "estrella.png",
                            Name = "Estrella Galicia",
                            OfficialWebsite = "https://estrellagalicia00.es/"
                        },
                        new
                        {
                            Id = 5,
                            Logo = "michelin.png",
                            Name = "Michelin",
                            OfficialWebsite = "https://www.michelinmotorsport.com/en/motorsport/"
                        },
                        new
                        {
                            Id = 6,
                            Logo = "dhl.png",
                            Name = "DHL",
                            OfficialWebsite = "https://www.dhl.com/global-en/home/about-us/partnerships.html"
                        });
                });

            modelBuilder.Entity("MotoGP.API.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Logo = "Avintia.png",
                            Name = "Avintia Racing"
                        },
                        new
                        {
                            Id = 2,
                            Logo = "AB.png",
                            Name = "Cardion AB Motoracing"
                        },
                        new
                        {
                            Id = 3,
                            Logo = "Ducati.png",
                            Name = "Ducati Team"
                        },
                        new
                        {
                            Id = 4,
                            Logo = "LCR.png",
                            Name = "LCR Honda MotoGP"
                        },
                        new
                        {
                            Id = 5,
                            Logo = "Repsol.png",
                            Name = "Repsol Honda Team"
                        },
                        new
                        {
                            Id = 6,
                            Logo = "M7.png",
                            Name = "Drive M7 Aspar"
                        },
                        new
                        {
                            Id = 7,
                            Logo = "ioda.png",
                            Name = "IodaRacing Project"
                        });
                });

            modelBuilder.Entity("Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("TeamSponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamSponsors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SponsorId = 2,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            SponsorId = 3,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            SponsorId = 4,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            SponsorId = 5,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            SponsorId = 6,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 6,
                            SponsorId = 1,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            SponsorId = 3,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 8,
                            SponsorId = 4,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 9,
                            SponsorId = 5,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 10,
                            SponsorId = 6,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 11,
                            SponsorId = 1,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 12,
                            SponsorId = 2,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 13,
                            SponsorId = 4,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 14,
                            SponsorId = 5,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 15,
                            SponsorId = 6,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 16,
                            SponsorId = 1,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 17,
                            SponsorId = 2,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 18,
                            SponsorId = 3,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 19,
                            SponsorId = 5,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 20,
                            SponsorId = 6,
                            TeamId = 4
                        });
                });

            modelBuilder.Entity("MotoGP.API.Entities.Rider", b =>
                {
                    b.HasOne("MotoGP.API.Entities.Country", "Country")
                        .WithMany("Riders")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoGP.API.Entities.Team", "Team")
                        .WithMany("Riders")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamSponsor", b =>
                {
                    b.HasOne("MotoGP.API.Entities.Sponsor", "Sponsor")
                        .WithMany("TeamSponsors")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoGP.API.Entities.Team", "Team")
                        .WithMany("TeamSponsors")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sponsor");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("MotoGP.API.Entities.Country", b =>
                {
                    b.Navigation("Riders");
                });

            modelBuilder.Entity("MotoGP.API.Entities.Sponsor", b =>
                {
                    b.Navigation("TeamSponsors");
                });

            modelBuilder.Entity("MotoGP.API.Entities.Team", b =>
                {
                    b.Navigation("Riders");

                    b.Navigation("TeamSponsors");
                });
#pragma warning restore 612, 618
        }
    }
}
